// Copyright 2024-2026 Solace Corporation. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package audit

import (
	"math"
	"strings"
	"testing"
)

// Hash-stability goldens (SOL-152090).
//
// Each case states the RFC 8785 canonical form by hand, derived from the
// specification's rules — recursive lexicographic key ordering by UTF-16 code
// unit, ES6 number serialisation, array order preserved, only the mandatory
// escapes — and the SHA-256 of exactly those bytes, computed OUTSIDE Go
// (python3 hashlib over the canonical string, no trailing newline).
//
// That independence is the point. A golden generated by running the code under
// test would pass no matter what the canonicaliser did; these fail if the
// canonicaliser's output ever changes, which is exactly the silent
// hash-divergence a customer could not reproduce.
var hashGoldens = []struct {
	name string
	args map[string]any
	// canonical is documentation of what the digest is over, and the value a
	// reader can re-hash themselves to check the fixture.
	canonical string
	want      string
}{
	{
		name:      "empty map",
		args:      map[string]any{},
		canonical: `{}`,
		want:      "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
	},
	{
		name:      "keys are sorted",
		args:      map[string]any{"b": 1, "a": 2},
		canonical: `{"a":2,"b":1}`,
		want:      "d3626ac30a87e6f7a6428233b3c68299976865fa5508e4267c5415c76af7a772",
	},
	{
		name: "a typical destructive call",
		args: map[string]any{
			"broker": "prod-1", "queueName": "orders/v1", "force": true, "count": 42,
		},
		canonical: `{"broker":"prod-1","count":42,"force":true,"queueName":"orders/v1"}`,
		want:      "a3134dfcbe328174efbc0bad1443ac355d7231b72a9c03e4c06bf83327f998e0",
	},
	{
		// Nested maps are sorted recursively; array element order is NOT
		// touched, and an explicit null is preserved rather than dropped.
		name: "nested maps sorted, arrays and nulls preserved",
		args: map[string]any{
			"z": []any{3, 1, 2},
			"n": nil,
			"m": map[string]any{"y": 1, "x": 2},
		},
		canonical: `{"m":{"x":2,"y":1},"n":null,"z":[3,1,2]}`,
		want:      "22a64e4706f978b672fb5b6b629a1abfa6bf06e21f707f7ae7ae92cfbf572c59",
	},
	{
		// Go's encoding/json escapes <, > and & to <, > and & by
		// default. RFC 8785 does not. If that escaping ever leaked into the
		// digest, every hash over an argument containing one of those
		// characters would be unreproducible by any conformant implementation —
		// and nothing else in this suite would notice.
		name:      "Go's HTML escaping does not reach the digest",
		args:      map[string]any{"k": "a<b&c>d"},
		canonical: `{"k":"a<b&c>d"}`,
		want:      "7ea7dc90e70de44a5749872fc3495b4d44155e3ff3170ad5f75c8c0206ea6c5c",
	},
	{
		// Ordering is by UTF-16 code unit, not by Go byte comparison or
		// case-insensitive collation: "Upper" (U+0055) sorts before the
		// lowercase keys, and the non-ASCII value survives as UTF-8.
		name:      "key order is by UTF-16 code unit",
		args:      map[string]any{"emoji": "\U0001F600", "ascii": "z", "Upper": "A"},
		canonical: "{\"Upper\":\"A\",\"ascii\":\"z\",\"emoji\":\"\U0001F600\"}",
		want:      "24d1957ba50dc584e796782528c429c3a30e7c50f649a0fd4aacca79e6008072",
	},
	{
		name:      "integers and fractions use ES6 serialisation",
		args:      map[string]any{"i": 100, "n": 1.5},
		canonical: `{"i":100,"n":1.5}`,
		want:      "78462c33540c988fabc936ab9f3a1df4ad9e81a13b777be7bd9def29ddc7524d",
	},
	{
		// The second independent leg under the RFC 8785 dependency. Go already
		// sorts ASCII map keys, so most cases above would survive removing the
		// canonicaliser entirely; number formatting would not. RFC 8785
		// mandates ES6 JSON.stringify semantics — 1e+30 rather than
		// 1000000000000000000000000000000, the shortest round-tripping form of
		// a denormal, an integral float as "1" and not "1.0" — and that is
		// exactly what a customer's Python or Java implementation will produce.
		// A divergence here is the cross-language reproduction promise broken.
		name:      "ES6 number formatting, not Go's",
		args:      map[string]any{"big": 1e30, "small": 5e-324, "whole": float64(1)},
		canonical: `{"big":1e+30,"small":5e-324,"whole":1}`,
		want:      "c4a5b58619478cd23f9f041bcf9936e3acf8e26d0e2960c1df5f859de5e17487",
	},
}

func TestHashArgs_goldens(t *testing.T) {
	t.Parallel()
	for _, tc := range hashGoldens {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got, err := HashArgs(tc.args)
			if err != nil {
				t.Fatalf("HashArgs: %v", err)
			}
			if got != tc.want {
				t.Errorf("digest drifted.\n got: %s\nwant: %s\nover canonical form: %s\n"+
					"A change here means audit hashes this build emits cannot be reproduced "+
					"from hashes an earlier build emitted. It must be a deliberate, "+
					"schema-versioned decision.", got, tc.want, tc.canonical)
			}
		})
	}
}

// TestHashArgs_nilHashesAsEmptyObject pins that "no arguments" has one digest.
// tools/call carries arguments with omitempty, so a client sending no
// arguments field and a client sending {} must not split into two digests.
func TestHashArgs_nilHashesAsEmptyObject(t *testing.T) {
	t.Parallel()
	nilHash, err := HashArgs(nil)
	if err != nil {
		t.Fatalf("HashArgs(nil): %v", err)
	}
	emptyHash, err := HashArgs(map[string]any{})
	if err != nil {
		t.Fatalf("HashArgs(empty): %v", err)
	}
	if nilHash != emptyHash {
		t.Errorf("nil and empty map hash differently: %s vs %s", nilHash, emptyHash)
	}
}

// TestHashArgs_structurallyEqualArgumentsAgree is the reproducibility promise
// in miniature: two maps built by different code paths, carrying the same
// values, must produce the same digest. Numeric type is included because
// arguments arriving from json.Unmarshal are float64 while a hand-built map
// holds int — an auditor recomputing from the wire JSON must land on the same
// digest as the server did.
func TestHashArgs_structurallyEqualArgumentsAgree(t *testing.T) {
	t.Parallel()
	fromWire := map[string]any{"count": float64(42), "nested": map[string]any{"a": float64(1)}}
	handBuilt := map[string]any{"nested": map[string]any{"a": 1}, "count": 42}

	a, err := HashArgs(fromWire)
	if err != nil {
		t.Fatalf("HashArgs(fromWire): %v", err)
	}
	b, err := HashArgs(handBuilt)
	if err != nil {
		t.Fatalf("HashArgs(handBuilt): %v", err)
	}
	if a != b {
		t.Errorf("structurally equal arguments hashed differently: %s vs %s", a, b)
	}
}

// TestHashArgs_differentArgumentsDiffer guards the assertion an auditor
// actually relies on: the digest identifies THESE arguments. A canonicaliser
// that dropped a field, or a hash taken over a constant, would pass every
// golden above and fail here.
func TestHashArgs_differentArgumentsDiffer(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		a, b map[string]any
	}{
		{"different value", map[string]any{"q": "orders"}, map[string]any{"q": "payments"}},
		{"different key", map[string]any{"q": "orders"}, map[string]any{"r": "orders"}},
		{"extra key", map[string]any{"q": "orders"}, map[string]any{"q": "orders", "force": true}},
		{"nested difference", map[string]any{"m": map[string]any{"x": 1}}, map[string]any{"m": map[string]any{"x": 2}}},
		{"array order", map[string]any{"a": []any{1, 2}}, map[string]any{"a": []any{2, 1}}},
		{"null vs absent", map[string]any{"q": nil}, map[string]any{}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			ha, err := HashArgs(tc.a)
			if err != nil {
				t.Fatalf("HashArgs(a): %v", err)
			}
			hb, err := HashArgs(tc.b)
			if err != nil {
				t.Fatalf("HashArgs(b): %v", err)
			}
			if ha == hb {
				t.Errorf("distinguishable arguments collided on digest %s", ha)
			}
		})
	}
}

// TestHashArgs_unrepresentableArgumentsError pins that a value JSON cannot
// carry produces an error, not a digest that stands for nothing. Unreachable
// from the production path (arguments always come from json.Unmarshal), so the
// test is the only thing holding the contract for a future caller.
func TestHashArgs_unrepresentableArgumentsError(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name string
		args map[string]any
	}{
		{"NaN", map[string]any{"n": math.NaN()}},
		{"positive infinity", map[string]any{"n": math.Inf(1)}},
		{"channel", map[string]any{"c": make(chan int)}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got, err := HashArgs(tc.args)
			if err == nil {
				t.Fatalf("HashArgs returned digest %q, want an error", got)
			}
			if got != "" {
				t.Errorf("HashArgs returned digest %q alongside an error; must return no digest", got)
			}
		})
	}
}

// TestHashArgs_digestIsHexSHA256 pins the encoding an auditor's tooling parses:
// 64 lowercase hex characters.
func TestHashArgs_digestIsHexSHA256(t *testing.T) {
	t.Parallel()
	got, err := HashArgs(map[string]any{"queueName": "orders/v1"})
	if err != nil {
		t.Fatalf("HashArgs: %v", err)
	}
	if len(got) != 64 {
		t.Errorf("digest is %d chars, want 64 (hex SHA-256): %q", len(got), got)
	}
	if strings.ToLower(got) != got {
		t.Errorf("digest is not lowercase hex: %q", got)
	}
	if strings.Trim(got, "0123456789abcdef") != "" {
		t.Errorf("digest contains non-hex characters: %q", got)
	}
}

// TestHashArgs_doesNotMutateCaller guards the caller's map: arguments are still
// dispatched to the handler after hashing, so a canonicaliser that sorted or
// rewrote the map in place would change what the tool actually executes.
func TestHashArgs_doesNotMutateCaller(t *testing.T) {
	t.Parallel()
	args := map[string]any{"b": 1, "a": map[string]any{"y": 2, "x": 3}}
	if _, err := HashArgs(args); err != nil {
		t.Fatalf("HashArgs: %v", err)
	}
	if len(args) != 2 {
		t.Fatalf("HashArgs changed the caller's map size to %d", len(args))
	}
	nested, ok := args["a"].(map[string]any)
	if !ok || len(nested) != 2 || nested["y"] != 2 || nested["x"] != 3 {
		t.Errorf("HashArgs mutated the caller's nested map: %#v", args["a"])
	}
}
